# Build customization
builds:
  - id: coder
    main: ./cmd/coder/main.go
    binary: coder
    goos:
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
  - id: findhash
    main: ./cmd/findhash/main.go
    binary: findhash
    goos:
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
  - id: hasher
    main: ./cmd/hasher/main.go
    binary: hasher
    goos:
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
# Archive customization
archives:
  - id: tgz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    files:
      - README.md
      - LICENSE
