[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/andrew-d/go-termutil"

[[constraint]]
  branch = "master"
  name = "github.com/aybabtme/color"

[[constraint]]
  branch = "master"
  name = "github.com/bproctor/base91"

[[constraint]]
  branch = "master"
  name = "github.com/cxmcc/tiger"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/blake256"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/blake2b"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/blake2s"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/blake512"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/siphash"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/skein"

[[constraint]]
  branch = "master"
  name = "github.com/google/gofuzz"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/crc16"

[[constraint]]
  branch = "master"
  name = "github.com/jbenet/go-base58"

[[constraint]]
  branch = "master"
  name = "github.com/jzelinskie/whirlpool"

[[constraint]]
  branch = "master"
  name = "github.com/martinlindhe/base36"

[[constraint]]
  branch = "master"
  name = "github.com/martinlindhe/bubblebabble"

[[constraint]]
  branch = "master"
  name = "github.com/martinlindhe/crc24"

[[constraint]]
  branch = "master"
  name = "github.com/martinlindhe/gogost"

[[constraint]]
  branch = "master"
  name = "github.com/mewpkg/hashutil"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/tilinna/z85"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"
